require("__tenebris-prime__.prototypes.entity.resources")
require("__tenebris-prime__.prototypes.autoplace_controls")
require("__tenebris-prime__.prototypes.planet.planet")
require("__tenebris-prime__.prototypes.item.item")
require("__tenebris-prime__.prototypes.entity.plants")
require("__tenebris-prime__.prototypes.recipe")
require("__tenebris-prime__.prototypes.entity.enemies.centipede")
require("__tenebris-prime__.prototypes.tile.tiles-tenebris")
require("__tenebris-prime__.prototypes.item_groups")
require("__tenebris-prime__.prototypes.technology")
require("__tenebris-prime__.prototypes.entity.entities")
require("__tenebris-prime__.prototypes.burner-usage")
require("__tenebris-prime__.prototypes.recipe-category")
require("__tenebris-prime__.prototypes.fuel-category")
require("__tenebris-prime__.prototypes.tips-and-tricks")
require("__tenebris-prime__.prototypes.entity.decorative")


require("__tenebris-prime__.prototypes.bioluminescent")
