local item_sounds = require("__base__.prototypes.item_sounds")
local space_age_item_sounds = require("__space-age__.prototypes.item_sounds")
local item_tints = require("__base__.prototypes.item-tints")
local meld = require("meld")

local ticks_per_minute = 60 * 60


local lightless_science_pack = meld(
    table.deepcopy(data.raw["tool"]["automation-science-pack"]), {
        name = "lightless-science-pack",
        icon = "__space-age__/graphics/icons/promethium-science-pack.png",
        subgroup = "science-pack",
        order = "t[tenebris]-a[lightless_science_pack]",
        pictures = meld.overwrite {
            scale = 0.5,
            size = 64,
            filename = "__space-age__/graphics/icons/promethium-science-pack.png",
            draw_as_glow = true,
        }
    })

local bioluminescent_science_pack = meld(
    table.deepcopy(data.raw["tool"]["automation-science-pack"]), {
        name = "bioluminescent-science-pack",
        icon = "__tenebris-prime__/graphics/icons/bioluminescent-science-pack.png",
        subgroup = "science-pack",
        order = "t[tenebris]-b[bioluminescent_science_pack]",
        pictures = meld.overwrite {
            scale = 0.5,
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/bioluminescent-science-pack.png",
            draw_as_glow = true,
        },
        spoil_result = "lightless-science-pack",
        spoil_ticks = ticks_per_minute * 120
    })

data:extend({
    {
        type = "item",
        name = "observation-satellite",
        icon = "__base__/graphics/icons/satellite.png",
        subgroup = "deep-space-sensing",
        inventory_move_sound = item_sounds.mechanical_inventory_move,
        pick_sound = item_sounds.mechanical_inventory_pickup,
        drop_sound = item_sounds.mechanical_inventory_move,
        stack_size = 1,
        weight = 1 * tons,
        send_to_orbit_mode = "automated"
    },
    {
        type = "item",
        name = "lucifunnel",
        subgroup = "tenebris-processes",
        stack_size = 50,
        icon = "__tenebris-prime__/graphics/icons/lucifunnel.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/lucifunnel.png",
            scale = 0.5,
            draw_as_glow = true,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        weight = 2 * kg,
        default_import_location = "tenebris",
        fuel_category = "chemical", 
        fuel_value = "4MJ", 
        spoil_result = "spoilage", 
        spoil_ticks = ticks_per_minute * 15
    },
    {
        type = "item",
        name = "lucifunnel-seed",
        localised_name = { "item-name.lucifunnel-seed" },
        icon = "__tenebris-prime__/graphics/icons/lucifunnel-seed.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/lucifunnel-seed.png",
            scale = 0.5,
            mipmap_count = 4,
            draw_as_glow = true
        },
        subgroup = "tenebris-processes",
        inventory_move_sound = item_sounds.wood_inventory_move,
        plant_result = "lucifunnel",
        place_result = "lucifunnel",
        stack_size = 10,
        default_import_location = "tenebris",
        fuel_category = "chemical",
        fuel_value = "100kJ",
        weight = 10 * kg,
    },
    {
        type = "item",
        name = "tenecap",
        subgroup = "tenebris-processes",
        stack_size = 50,
        icon = "__tenebris-prime__/graphics/icons/tenecap.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/tenecap.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        weight = weight or (2 * kg),
        default_import_location = "tenebris",
        spoil_result = "tenecap-spore", 
        spoil_ticks = ticks_per_minute * 20
    },
    {
        type = "item",
        name = "tenecap-spore",
        localised_name = { "item-name.tenecap-spore" },
        icon = "__tenebris-prime__/graphics/icons/tenecap-spore.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/tenecap-spore.png",
            scale = 0.5,
        },
        subgroup = "tenebris-processes",
        inventory_move_sound = item_sounds.wood_inventory_move,
        plant_result = "tenecap",
        place_result = "tenecap",
        stack_size = 20,
        default_import_location = "tenebris",
        fuel_category = "chemical",
        fuel_value = "100kJ",
        weight = 5 * kg,
    },
    {
        type = "item",
        name = "sulfuric-waste-spores",
        icon = "__tenebris-prime__/graphics/icons/tenecap-spore.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/tenecap-spore.png",
            scale = 0.5,
        },
        subgroup = "tenebris-processes",
        inventory_move_sound = item_sounds.wood_inventory_move,
        stack_size = 20,
        default_import_location = "tenebris",
        fuel_category = "chemical",
        fuel_value = "100kJ",
        weight = 5 * kg,
    },
    {
        type = "item",
        name = "quartz-ore",
        icon = "__tenebris-prime__/graphics/icons/quartz-ore.png",
        subgroup = "tenebris-processes",
        pictures =
        {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/quartz-ore.png",
            scale = 0.5,
            mipmap_count = 4,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        default_import_location = "tenebris",
        stack_size = 50,
        weight = 2 * kg
    },
    {
        type = "item",
        name = "luciferin",
        subgroup = "tenebris-processes",
        icon = "__tenebris-prime__/graphics/icons/luciferin.png",
        stack_size = 100,
        fuel_category = "chemical",
        fuel_value = "1MJ",
        pictures = {
            scale = 0.5,
            width = 64,
            height = 64,
            filename = "__tenebris-prime__/graphics/icons/luciferin.png",
            draw_as_glow = true,
        },
        default_import_location = "tenebris",
    },
    {
        type = "item",
        name = "chitin",
        subgroup = "tenebris-processes",
        stack_size = 50,
        icon = "__tenebris-prime__/graphics/icons/chitin.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/chitin.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        weight = 2 * kg,
        default_import_location = "tenebris",
    },
    {
        type = "item",
        name = "chitosan",
        subgroup = "tenebris-processes",
        stack_size = 50,
        icon = "__tenebris-prime__/graphics/icons/chitosan.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/chitosan.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        weight = 2 * kg,
        default_import_location = "tenebris",
    },
    {
        type = "item",
        name = "quartz-crystal",
        subgroup = "tenebris-processes",
        stack_size = 100,
        icon = "__tenebris-prime__/graphics/icons/quartz-crystal.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/quartz-crystal.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.rock_inventory_move,
        pick_sound = item_sounds.rock_inventory_pickup,
        drop_sound = item_sounds.rock_inventory_move,
        weight = 2 * kg,
        default_import_location = "tenebris",
    },
    {
        type = "item",
        name = "quartz-crystal-seedling",
        subgroup = "tenebris-processes",
        stack_size = 5,
        icon = "__tenebris-prime__/graphics/entity/quartz-node/quartz-node-2.png",
        icon_size = 256,
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/entity/quartz-node/quartz-node-2.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.rock_inventory_move,
        pick_sound = item_sounds.rock_inventory_pickup,
        drop_sound = item_sounds.rock_inventory_move,
        plant_result = "quartz-node",
        place_result = "quartz-node",
        weight = 0.5 * kg,
        default_import_location = "tenebris",
        spoil_result = "quartz-crystal", 
        spoil_ticks = ticks_per_minute * 6
    },
    {
        type = "item",
        name = "photonic-crystal",
        subgroup = "tenebris-processes",
        stack_size = 100,
        icon = "__tenebris-prime__/graphics/icons/quartz-crystal.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/quartz-crystal.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.rock_inventory_move,
        pick_sound = item_sounds.rock_inventory_pickup,
        drop_sound = item_sounds.rock_inventory_move,
        weight = 2 * kg,
        default_import_location = "tenebris",
    },
    {
        type = "item",
        name = "bioluminescent-crystal",
        subgroup = "tenebris-processes",
        stack_size = 100,
        icon = "__tenebris-prime__/graphics/icons/bioluminescent-crystal.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/bioluminescent-crystal.png",
            scale = 0.5,
            draw_as_glow = true,
        },
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        weight = 2 * kg,
        default_import_location = "tenebris",
        fuel_category = "bioluminescent", 
        fuel_value = "100kJ"
    },
    {
        type = "item",
        name = "bismuth-ore",
        subgroup = "tenebris-processes",
        icon = "__base__/graphics/icons/copper-ore.png",
        pictures = {
            size = 64,
            filename = "__base__/graphics/icons/copper-ore.png",
            scale = 0.5,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 4 * kg
    },
    {
      type = "item",
      name = "quartziferous-bismuthal-plate",
      icon = "__base__/graphics/icons/copper-plate.png",
      subgroup = "tenebris-processes",
      inventory_move_sound = item_sounds.metal_small_inventory_move,
      pick_sound = item_sounds.metal_small_inventory_pickup,
      drop_sound = item_sounds.metal_small_inventory_move,
      stack_size = 100
    },
    {
        type = "item",
        name = "tenebris-bioinfusor",
        subgroup = "bioluminescent-production-machine",
        order = "t[tenebris]-a[tenebris-bioinfusor]",
        stack_size = 10,
        icon = "__tenebris-prime__/graphics/icons/tenebris-bioinfusor.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/tenebris-bioinfusor.png",
            scale = 0.5,
            draw_as_glow = true,
        },
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        weight = 100 * kg,
        default_import_location = "tenebris",
        place_result = "tenebris-bioinfusor"
    },
    {
        type = "item",
        name = "tenebris-biobeacon",
        subgroup = "bioluminescent-production-machine",
        order = "t[tenebris]-b[tenebris-biobeacon]",
        stack_size = 10,
        icon = "__tenebris-prime__/graphics/icons/tenebris-biobeacon.png",
        pictures = {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/tenebris-biobeacon.png",
            scale = 0.5,
            draw_as_glow = true,
        },
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        weight = 100 * kg,
        default_import_location = "tenebris",
        place_result = "tenebris-biobeacon"
    },
    {
        type = "module",
        name = "spore-removal-module",
        localised_description = {"item-description.speed-module"},
        icon = "__base__/graphics/icons/speed-module.png",
        subgroup = "module",
        color_hint = { text = "S" },
        category = "efficiency",
        tier = 3,
        order = "t[tenebris]-a[tenebris-spore-removal-module]",
        inventory_move_sound = item_sounds.module_inventory_move,
        pick_sound = item_sounds.module_inventory_pickup,
        drop_sound = item_sounds.module_inventory_move,
        stack_size = 50,
        weight = 20 * kg,
        effect = {pollution = 0.3, consumption = 0.5},
        beacon_tint =
        {
          primary = {0.423, 0.0, 0.632, 1.000}, -- #6C00A1FF
          secondary = {0.631, 0.137, 0.82, 1.000}, -- #A123D1FF
        },
        default_import_location = "tenebris",
        art_style = "vanilla",
        requires_beacon_alt_mode = false
    },
    {
        type = "item",
        name = "tenebris-heated-air-scrubber",
        subgroup = "bioluminescent-production-machine",
        icon = "__atan-air-scrubbing__/graphics/icons/air-scrubber.png",
        inventory_move_sound = item_sounds.mechanical_inventory_move,
        pick_sound = item_sounds.mechanical_inventory_pickup,
        drop_sound = item_sounds.mechanical_inventory_move,
        place_result = "tenebris-heated-air-scrubber",
        stack_size = 20,
        weight = 50 * kg,
    },
    {
        type = "item",
        name = "tenebris-spore-filter",
        subgroup = "atan-filters",
        icon = "__atan-air-scrubbing__/graphics/icons/pollution-filter.png",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        stack_size = 50,
        weight = 10 * kg,
    },
    {
        type = "item",
        name = "tenebris-used-spore-filter",
        subgroup = "atan-filters",
        icon = "__atan-air-scrubbing__/graphics/icons/used-pollution-filter.png",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        stack_size = 50,
        weight = 15 * kg,
    },
    {
        type = "item",
        name = "lightless-beacon",
        icon = "__tenebris-prime__/graphics/icons/tenebris-biobeacon.png",
        pictures =
        {
            size = 64,
            filename = "__tenebris-prime__/graphics/icons/tenebris-biobeacon.png",
            scale = 0.5,
            draw_as_glow = true,
        },
        subgroup = "bioluminescent-production-machine",
        order = "t[tenebris]-c[lightless-beacon]",
        inventory_move_sound = item_sounds.electric_large_inventory_move,
        pick_sound = item_sounds.electric_large_inventory_pickup,
        drop_sound = item_sounds.electric_large_inventory_move,
        stack_size = 50,
        weight = 2 * kg
    },
    {
        type = "item",
        name = "bismuth-asteroid-chunk",
        icon = "__space-age__/graphics/icons/promethium-asteroid-chunk.png",
        subgroup = "space-material",
        order = "t[tenebris]-a[bismuth-asteroid-chunk]",
        inventory_move_sound = space_age_item_sounds.rock_inventory_move,
        pick_sound = space_age_item_sounds.rock_inventory_pickup,
        drop_sound = space_age_item_sounds.rock_inventory_move,
        stack_size = 1,
        weight = 100 * kg,
        random_tint_color = item_tints.iron_rust
    },
    bioluminescent_science_pack,
    lightless_science_pack,
})
