meld = require("meld")

local function order_data(type_name, group_ordering, data_name, order_variable)
    return meld(data.raw[type_name][data_name], {
        order = string.format("t[tenebris]-%s-%s[%s]", group_ordering, order_variable, data_name)
    })
end

local function build_group_ordering(group_name, group_order)
    return string.format("%s[%s]", group_order, group_name)
end

-- Items and Recipes
deep_space_sensing = build_group_ordering("deep-space-sensing", "a")
agriculture = build_group_ordering("agriculture", "b")
seeds = build_group_ordering("seeds", "c")
minerals = build_group_ordering("minerals", "d")
organic_products = build_group_ordering("organic-products", "e")
crystallization = build_group_ordering("crystallization", "f")
atmosphere_filtration = build_group_ordering("atmosphere-filtration", "g")
atmosphere_distillation = build_group_ordering("atmosphere-distillation", "h")
cryogenic_process = build_group_ordering("cryogenic-process", "i")
orbital_harvesting = build_group_ordering("orbital-harvesting", "j")
casting = build_group_ordering("casting", "k")
weaponry = build_group_ordering("weaponry", "l")
waste_burning = build_group_ordering("waste-burning", "m")

order_data("item", agriculture, "lucifunnel", "a")
order_data("item", agriculture, "tenecap", "b")

order_data("item", seeds, "lucifunnel-seed", "a")
order_data("recipe", seeds, "lucifunnel-processing", "b")
order_data("item", seeds, "tenecap-spore", "c")
order_data("recipe", seeds, "tenecap-processing", "d")

order_data("item", minerals, "quartz-ore", "a")
order_data("recipe", minerals, "tenebris-stone-centrifuging", "b")

order_data("item", organic_products, "luciferin", "a")
order_data("item", organic_products, "chitin", "b")
order_data("item", organic_products, "chitosan", "c")
order_data("recipe", organic_products, "chitin-processing", "d")
order_data("recipe", organic_products, "chitosan-advanced-circuit", "e")
order_data("recipe", organic_products, "chitin-concrete", "f")
order_data("recipe", organic_products, "chitosan-lubricant", "g")
order_data("recipe", organic_products, "chitosan-carbon-fiber", "h")
order_data("recipe", organic_products, "chitin-processing", "i")

order_data("item", crystallization, "quartz-crystal", "a")
order_data("item", crystallization, "quartz-crystal-seedling", "b")
order_data("recipe", crystallization, "quartz-ore-washing", "c")
order_data("recipe", crystallization, "quartz-crystal-reduction", "d")
order_data("item", crystallization, "photonic-crystal", "e")
order_data("item", crystallization, "bioluminescent-crystal", "f")
order_data("recipe", crystallization, "bioluminescent-crystal-organics", "g")
order_data("recipe", crystallization, "bioluminescent-crystal-forging", "h")

order_data("item", atmosphere_filtration, "tenebris-heated-air-scrubber", "a")
order_data("item", atmosphere_filtration, "tenebris-spore-filter", "b")
order_data("item", atmosphere_filtration, "tenebris-used-spore-filter", "c")
order_data("recipe", atmosphere_filtration, "tenebris-atmosphere-scrubbing", "d")

order_data("recipe", atmosphere_distillation, "tenebris-atmosphere", "a")
order_data("recipe", atmosphere_distillation, "tenebris-atmosphere-separation", "b")
order_data("item", atmosphere_distillation, "sulfuric-waste-spores", "c")
order_data("recipe", atmosphere_distillation, "tenecap-spore-purification", "d")

order_data("recipe", cryogenic_process, "luciferin-solid-fuel", "a")
order_data("recipe", cryogenic_process, "luciferin-rocket-fuel", "b")
order_data("recipe", cryogenic_process, "sulfuric-fluoroketone", "c")
order_data("recipe", cryogenic_process, "luciferin-explosives", "d")
order_data("recipe", cryogenic_process, "ammonic-acidification", "e")

order_data("item", orbital_harvesting, "bismuth-ore", "a")
order_data("recipe", orbital_harvesting, "bismuth-asteroid-crushing", "b")

order_data("recipe", casting, "bismuth-ore-melting", "a")
order_data("item", casting, "quartziferous-bismuthal-plate", "b")

order_data("recipe", waste_burning, "lucifunnel-burning", "a")
order_data("recipe", waste_burning, "chitin-burning", "b")

order_data("item", deep_space_sensing, "observation-satellite", "a")
order_data("recipe", deep_space_sensing, "observation-satellite", "b")

-- Technologies
tenebris_tech = build_group_ordering("tenebris-tech", "a")

order_data("technology", tenebris_tech, "deep-space-sensing", "aa")
order_data("technology", tenebris_tech, "planet-discovery-tenebris", "ab")
order_data("technology", tenebris_tech, "lucifunnel-processing", "ac")
order_data("technology", tenebris_tech, "tenecap-processing", "ad")
order_data("technology", tenebris_tech, "quartz-ore", "ae")
order_data("technology", tenebris_tech, "quartz-crystal", "af")
order_data("technology", tenebris_tech, "tenebris-atmosphere-separation", "ag")
order_data("technology", tenebris_tech, "chitin-processing", "ah")
order_data("technology", tenebris_tech, "lightless-science-pack", "ai")
order_data("technology", tenebris_tech, "deep-space-discovery-iridescent-river", "aj")
order_data("technology", tenebris_tech, "lightless-beacons", "ak")
order_data("technology", tenebris_tech, "luciferin-explosives", "al")
order_data("technology", tenebris_tech, "luciferin-rocketry-speed", "am")
order_data("technology", tenebris_tech, "quartz-crystal-reduction", "an")
order_data("technology", tenebris_tech, "tenebris-soil-enrichment", "ao")
order_data("technology", tenebris_tech, "ammonic-acidification", "ap")
order_data("technology", tenebris_tech, "sulfuric-ketones", "aq")
order_data("technology", tenebris_tech, "bioluminescent-crystal", "ar")
order_data("technology", tenebris_tech, "tenebris-bioinfusor", "as")
order_data("technology", tenebris_tech, "bioluminescent-science-pack", "at")
order_data("technology", tenebris_tech, "photonic-derangement", "au")
order_data("technology", tenebris_tech, "bismuthal-alloys", "av")
order_data("technology", tenebris_tech, "tenebris-biobeacon", "aw")
order_data("technology", tenebris_tech, "tenebris-laser-cannon", "ax")
order_data("technology", tenebris_tech, "tenebris-laser-shooting-speed", "ay")
order_data("technology", tenebris_tech, "tenebris-beacon-distribution-efficiency", "az")
order_data("technology", tenebris_tech, "cloaking", "ba")
order_data("technology", tenebris_tech, "bioluminescent-robots", "bb")
order_data("technology", tenebris_tech, "worker-robot-battery-capacity", "bc")
order_data("technology", tenebris_tech, "bioluminescent-lamps", "bd")
order_data("technology", tenebris_tech, "deep-space-discovery-lightless-abyss", "be")