local tenebris_asteroid_util = require("__tenebris-prime__.prototypes.planet.asteroid-spawn-definitions")
local constants = require("lib.constants")

data:extend({
    {
        type = "space-connection",
        name = "fulgora-tenebris",
        subgroup = "planet-connections",
        from = "fulgora",
        to = constants.PLANET.TENEBRIS,
        length = 75000,
        asteroid_spawn_definitions = tenebris_asteroid_util.spawn_definitions(tenebris_asteroid_util.fulgora_tenebris),
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
    {
        type = "space-connection",
        name = "tenebris-iridescent-river",
        subgroup = "planet-connections",
        from = constants.PLANET.TENEBRIS,
        to = "iridescent-river",
        length = 62000,
        asteroid_spawn_definitions = tenebris_asteroid_util.spawn_definitions(tenebris_asteroid_util.tenebris_iridescent_river),
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
    {
        type = "space-connection",
        name = "iridescent-river-the-nest",
        subgroup = "planet-connections",
        from = "iridescent-river",
        to = "the-nest",
        length = 50000,
        asteroid_spawn_definitions = tenebris_asteroid_util.spawn_definitions(tenebris_asteroid_util.the_nest_route),
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
    {
        type = "space-connection",
        name = "tenebris-the-nest",
        subgroup = "planet-connections",
        from = constants.PLANET.TENEBRIS,
        to = "the-nest",
        length = 80000,
        asteroid_spawn_definitions = tenebris_asteroid_util.spawn_definitions(tenebris_asteroid_util.the_nest_route),
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
    {
        type = "space-connection",
        name = "iridescent-river-lightless-gateway",
        subgroup = "planet-connections",
        from = "iridescent-river",
        to = "lightless-gateway",
        length = 100000,
        asteroid_spawn_definitions = tenebris_asteroid_util.spawn_definitions(tenebris_asteroid_util.tenebris_lightless_abyss),
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
    {
        type = "space-connection",
        name = "the-nest-lightless-gateway",
        subgroup = "planet-connections",
        from = "the-nest",
        to = "lightless-gateway",
        length = 70000,
        asteroid_spawn_definitions = tenebris_asteroid_util.spawn_definitions(tenebris_asteroid_util.tenebris_lightless_abyss),
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
    {
        type = "space-connection",
        name = "lightless-gateway-lightless-abyss",
        subgroup = "planet-connections",
        from = "lightless-gateway",
        to = "lightless-abyss",
        length = 9000000,
        asteroid_spawn_definitions = {},
        tenebris_prime_connection = true,
        redrawn_connections_exclude = true,
    },
})
